//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Randal.Tests.Sql.Deployer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Randal.Tests.Sql.Deployer.TestScripts", typeof(TestScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* a broken comment
        ///select Name from Employee.
        /// </summary>
        public static string BrokenScript {
            get {
                return ResourceManager.GetString("BrokenScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- drop table A
        ////* drop table B;*/
        ///exec dropSomeData
        ///-- exec(&apos;print &apos;&apos;test&apos;&apos;&apos;)
        ////* exec (&apos;print &apos;&apos;test&apos;&apos;&apos;) */
        ///exec [truncate]
        ///select * from dbo.drop().
        /// </summary>
        public static string SafeScript {
            get {
                return ResourceManager.GetString("SafeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop table C;
        ///exec
        ///(&apos;drop database master&apos;)
        ///exec(&apos;select 1&apos;)
        ///truncate table Test.
        /// </summary>
        public static string UnsafeScript {
            get {
                return ResourceManager.GetString("UnsafeScript", resourceCulture);
            }
        }
    }
}
